### ISSUE TITLE
Can't interact with stuffs in Mario Sports Superstars' or Pokémon Moon's game filesystems

### ISSUE THREAD

**Issue by SvenDaHacker64** [d0k3/GodMode9#102]
So, I mounted the .app (A:title/00040000/00188d00) as NCCH image/drive, then it shows up the following .bin files: exefs, extheader, logo, ncch, plain, and romfs, no folders.

I would like exploring game files inside RomFS.

Whenever I try to copy one of the files to 0:/gm9out (export to SD), it says "Failed copying item". It also fails to export files from other .app file in same game (with few MB's filesize), even I manually press Y on it then copy somewhere else in SD card.
Works fine on other digital games - most were installed using freeShop of course.

Pokemon Moon doesn't let me export files either.

**Comment by d0k3** [comment]
I'm pretty sure this doesn't happen with all files in the RomFS filesystem. Can you give me the full path of one of the files that can't be copied? Any chance it contains illegal chars in the filename (':', '?', '*', '/', '\') or in the containing dirs?

**Comment by SvenDaHacker64** [comment]
For Pokémon Moon, I can't copy:
exefs.bin
romfs.bin

I can copy these now:
extheader.bin
logo.bin
ncch.bin
plain.bin


For Mario Sports Superstars:
It seems to work fine, the \exefs and \romfs directories are now visible, all other files are copyable. That's weird.

No illegal characters in filenames are found.

**Comment by d0k3** [comment]
Okay, let's think up an explanation, shall we?

What is your entry point, is it perhaps something older than boot9strap v1.2? Are you using the most recent release of GodMode9. Also, is there any chance you don't have the aeskeydb.bin file / updated it in the meantime? What is the region of your console, and what is the region of these two titles.

A missing aeskeydb.bin file, on an older entrypoint (A9LH, too) can explain why the ExeFS and RomFS dirs didn't show up earlier (they did not because we can't decrypt them without keys).

Now, I tried both titles (Pokemon Moon & Mario Sports Superstars), found no problems. Everything works and copies fine. So, the problem may be on your side. Maybe your 'B' button is malfunctioning and your cancelling the copy without your knowledge? Maybe there's some problem with your SD card?

Anyways, the most recent nightly may help, try it and tell me if that changes anything for you:
https://transfer.sh/3dzDm/GodMode9-20170630-010802.zip

Take note that the standard output path is 0:/gm9/out for the nightly, no more 0:/gm9out.

**Comment by SvenDaHacker64** [comment]
I use B9S 1.2 method. GodMode9 is 1.2.1, latest one. My system is EUR, along two games. aeskeydb.bin still exists in /files9

I figured out that updating SeedDB using your Decrypt9WIP fixes the problem and now shows romfs and exefs directories! Of course it successfully copied to 0:/gm9out.
