### ISSUE TITLE
Feature Request - Option to unmount sd card by pressing the home button

### ISSUE THREAD

**Issue by mmands994** [d0k3/GodMode9#113]
Just for those users with a broken R button.

**Comment by AidenTheCuber** [comment]
Please do it!

**Comment by Jan200101** [comment]
How about being able to code a sd unmount ?

**Comment by d0k3** [comment]
I get requests for special "broken console" special builds often, and tbh, I can't even start to fulfill them. You've got a broken R button, the next guy has a broken L button, and some people may even miss the whle ABXY row.

I instead help you to help yourself. See this source file?
https://github.com/d0k3/GodMode9/blob/master/source/common/hid.h#L12-L23

Swap the definition of your broken button with one that works, one that you don't need otherwise. Compile and run from your console. If you can't do this, ask someone mrope knowledgeable.
