### ISSUE TITLE
3dsx version does not work

### ISSUE THREAD

**Issue by Anggeloko** [d0k3/GodMode9#134]
I was trying the 3dsx version but it does not work (I'm using Rosalina)
I have the files in: 3ds/GodMode9/(GodMode9.3dsx and .smdh)
The screen turns black and returns to the homebrew menu
I hope you can help me 👍

**Comment by ValliantStorme** [comment]
The 3DSX version of GodMode9 is not designed to be usable from Rosalina, and is on the verge of being permanently discontinued.

You should run GodMode9 from Luma3DS's payload selector. (put godmode9.firm in /luma/payloads and launch it by holding START on boot)

**Comment by Anggeloko** [comment]
The payload works perfectly, but when viewing the version in 3dsx I thought it would serve in rosalina, as it launches the homebrew launcher from any app :(

**Comment by ValliantStorme** [comment]
The Homebrew Launcher is only for launching Arm11 homebrew. It isn't capable of launching Arm9 homebrew, which GodMode9 is.

The only reason GM9 has a 3dsx build is because, in the past, there was no such thing as the Luma Chainloader, or Boot9Strap, or Arm9Loaderhax. It could only be launched by using a now outdated exploit from the Arm11.

Since that exploit and variants of it have been patched (many times) by Ninty, the 3dsx build is useless on modern firmwares. It's being completely removed on the next release of GodMode9.

**Comment by d0k3** [comment]
@ValliantStorme is perfectly right. That 3dsx would work on 9.0 to 9.2, but nowhere else. It would also be unstable and a hassle to use. To put things short, don't use it. Use the firm payload with the chainloader.

**Comment by Anggeloko** [comment]
Oh thank you both, close this
