### ISSUE TITLE
RAM VIRTUAL can be upgrade via GodMode9?

### ISSUE THREAD

**Issue by Bolt23** [d0k3/GodMode9#218]
I don't know much but was thinking if can increase the size of 63.9 MB of Ram by flashing something or the other. Maybe from SD card or NHSD? (whatever) just like page file in Windows. I am right or wrong?

**Comment by d0k3** [comment]
You're wrong. 64MB is in the RAM of your console, and that's a hard limit there.

**Comment by Bolt23** [comment]
What about overclocking the CPU to severe limit which might even fry the motherboard OR increase performance when being charged just like high performance mode in PCs? Still wrong right?

**Comment by ValliantStorme** [comment]
You know what RAM is, right?

**Comment by Bolt23** [comment]
No! :( Sadly I don't know that it is Random Access Memory and is cleared out each time the power is off and PC shutdowns and does not store any data. I don't know that it is an integrated chip that allows processes to be run on it by using it Memory! I don't know that it is not like HD that it can be increased or decreased! Though Pagefile, to which you are surely unknown can be increased on the HD for smooth memory allocation by RAM. Fie @ValliantStorme sadly you must be thinking that wish you could buy some brains if available in the market. 👍 Go for it maybe stores have Brains!

**Comment by ValliantStorme** [comment]
Yeah, great Google skills there. If only you'd used them before creating an issue.

Also, dude, don't take stuff so personally. You misinterpreted what "RAM VIRTUAL" meant, that's entirely OK, nobody's judging you for it (and if I came across as cynical or hateful, I'm sorry. It was supposed to be a joke making fun of "downloadmoreram.com", but looking back it did seem pretty harsh). 

But really, HDD and SSD storage is as fixed in size as RAM... It's all stored on some sort of physical storage somewhere (there's just usually a LOT more space on a hard drive than the 64MB of RAM that GM9 can spare for the ramdrive partition on a 3DS). If you want a partition on the 3DS's internal storage to use in GodMode9, (which is what it seems like you're looking for,) look in the Wiki for how to format your system to include a "bonus drive". If your 3DS's NAND has enough space for it, you might be able to get up to 800MB, depending on the model of 3DS you have.
