### ISSUE TITLE
Enhancement - Hide files beginning with .

### ISSUE THREAD

**Issue by v0idst4r** [d0k3/GodMode9#226]
Files beginning with . are hidden on linux, this will also prevent noobs from running information files generated by mac os.

**Comment by ZetaDesigns** [comment]
What about .code files in games?

**Comment by Jisagi** [comment]
He is talking about the ._ files which in the script folder.

**Comment by ZetaDesigns** [comment]
He phrased it like he means *every* file starting with .

**Comment by d0k3** [comment]
Yeah, @ZetaDesigns already pointed out a possible flaw with this. Files and folders starting with '.' may be hidden in Unix based OSes, but they are not in the 3DS OS, f.e.. I personally dislike hiding anything from view in what is an advanced file manager, too.

Just delete these unwanted files, or use FTP instead of a card reader to move files to your console. Won't be implemented, closing this now.

**Comment by jason0597** [comment]
@d0k3 a lot of noobs come in from 3ds.guide to the discord channel trying to backup their NAND, and a lot of them use macs. We have to manually tell them to not execute these files (keep in mind they have no idea what "terminal" means)
Perhaps make it so that the `gm9` folder provided in the zip contains some sort of configuration file, which when existant hides such `._` files, and upon deletion it shows them (and the only way to re-enable this is to manually copy the file from the GodMode9 release zip). This way, noobs are handled properly, and power users know what to do.

**Comment by d0k3** [comment]
These files are already ignored in the payloads and script menus, and they are also not recognized as any filetype. Executing them is impossible. Try it in the current nightly.
