### ISSUE TITLE
"AGBSAVE options" menu limited to SysNAND Virtual ?

### ISSUE THREAD

**Issue by Alex131089** [d0k3/GodMode9#269]
Hello, 

this might be a stupid question, but why is the `AGBSAVE options` menu limited to the `SysNAND Virtual (S:)` drive?
From what I saw, I can read the `.sav` in the data folder of GBA games, and it doesn't seems encrypted (at least the header magic is visible), the content seems the same as `S:/agbsave.bin`, so could the menu to dump&inject the content be present on thoses files too (and couldn't an homebrew do the same with the saves?)? Or am I missing something?
If it is a crypto issue, don't we have all keys needed ?

Alex

**Comment by d0k3** [comment]
Has already been discussed and you're missing something. Even if what you see `A:/` looks like it is identical to what you get on `S:/`, it in fact isn't. The savegame on the SD has two partitions, for which there is no reliable way to tell which one is the correct one. For freshly installed GBA VC games, the state of the savegame on SD is undefined.

In short, rather than providing some wonky, unreliable support for this, there will rather be no support at all. Use the `S:/agbave.bin`.
