### ISSUE TITLE
Multiple feature requests.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#273]
1.Add option to fill the file (no filling,fill with 00h or fill with FFh) when creating dummy files,so you can overwrite free regions in NANDs,and the resulting dump would compress better.FFh is because it is the "natural state" of NAND flash.
2.Hide the C: drive when a cart is not inserted.Show the internal NAND flash of flashcarts if it is available.Mainly for NTRflash.
3.Tidy up the online manual.Hide markdown symbols by default when reading MD files.

**Comment by d0k3** [comment]
1.  Well... how do you intend to fill these unused NAND regions in GodMode9? Keep in mind encrypted all 0x00 / 0xFF is as bad as encrypted randomness.
2. Handling flashcarts has been discussed at length. Some way to handle them may be added or not, but I won't do it, and I also won't take pull requests that only provide support for one or two brands. Hiding the cart drive comes with other problems, cause then I'd have to prevent all of the shenanigans that may lead to carts not being initialized despite them being in the slot. In short, really not worth it. You need the cart drive to force GM9 to check for a cart.
3. I'd understand if the `README.md` was written in HTML, but markdown is designed so that it is still perfectly readable in it's text form. Add to that that a on the fly string replacement would feature would either be slow or would mean a shitton of work. In short, the effort required would not be justified by the potential gain.

**Comment by fox8091** [comment]
The readme is copied into the VRAM drive at compile, right? If so, format as part of the Makefile using regex? Also, we have flashcart_core now, so supporting multiple DS carts is easy. Sky3DS (red or blue) have no way to access the filesystem. Sky3DS+ (orange) seems to have a way (or so the SkyDock suggests). Gateway is the most supported of 3DS carts, as it has a library already written and would support Gateway, DSTWO+, MT-Card, and all other Gateway clones.

**Comment by urherenow** [comment]
You are poorly mistaken. Just because someone tried to start a library, doesn't mean it WORKS. Anything you see in flashcart_core for GW is for just 1 of the at least 5 different blue cards floating around. DSTWO+ is not supported at all yet. What are you talking about "all other Gateway clones"? The Gateway red card has no library at all. Why would someone clone a GW blue cart? It's already a clone, and not even a specific one. It's the luck of the draw, which board is in your blue card, and there is no support unless you happen to have the one that's a clone of the Ace3ds+.

**Comment by urherenow** [comment]
You are poorly mistaken. Just because someone tried to start a library, doesn't mean it WORKS. Anything you see in flashcart_core for GW is for just 1 of the at least 5 different blue cards floating around. DSTWO+ is not supported at all yet. What are you talking about "all other Gateway clones"? The Gateway red card has no library at all. Why would someone clone a GW blue cart? It's already a clone, and not even a specific one. It's the luck of the draw, which board is in your blue card, and there is no support unless you happen to have the one that's a clone of the Ace3ds+.

**Comment by fox8091** [comment]
Uhm, when I mentioned Gateway, I meant the red card. ShinyQuagsire has a library for it published on GitHub.

**Comment by fox8091** [comment]
https://github.com/shinyquagsire23/gwcard There is code here to access the raw sectors of the SD, and that's all that's needed to implement a filesystem layer.

**Comment by urherenow** [comment]
Whoa! My apologies, I had no idea this existed. Thanks for the link!

**Comment by fox8091** [comment]
No problem. If I haven't taken it down, I have a fork with am abstraction layer on top.

**Comment by d0k3** [comment]
The problem with this is, again, that it supports only a specific set of cards. It may even be worse, though. Commands that have one function in one flashcart may have a completely different function in another. Think an identification command in one flashcart, which would equal an erase command in another (yes, that happens).

And yes, we have no surefire way of making sure a flashcart is of a specific model (that's why ntrboot_flasher makes you choose). That problem would be even worse in GM9, cause people would try it with each and every flashcart on the market.

That being said, I'm open to taking prs, condition is that it supports at least all ntrboot compatible cards and that *it is sufficiently safe*. Maybe DLDI is the way to go, I really don't know.

@fox8091 - sure, you could regex search and replace the `README.md`, but then, important info would go missing. Among that the info we need to build the ToC, emphasized parts of the text and enumerations. While being a compromise between two worlds (formatted and unformatted text), markdown still is perfectly readable in text form, and thus will stay that way.

Anyways, closing this now. @pthfdr-42 - one future feature requests and bug reports, please open one issue per topic.

**Comment by JudasFaye** [comment]
I have created a emunand by godmode9, and it will show an unformatted partition on my pc.
is it normal?
I remember there was no an unformatted partition when i use GWemu？
Anyone can help？

**Comment by Validusername16** [comment]
Why did you comment this on a pull request from 2017 😕 
But yes, that is normal.
