### ISSUE TITLE
initial sysNAND made by GodMode9 (reference)

### ISSUE THREAD

**Issue by Maxmeas** [d0k3/GodMode9#293]
By starting GodMode9 at thw first time the user will be prompted to make a file called essential.exefs.

By accepting the prompt a file will be created at “sdmc:/gm9/out” called essential.exefs.

If you delete essential.exefs on the sd, you won’t be asked again by GodMode9.

By comparing NAND dumps I found out that they have different sha1sum, if you made an essential.exefs.

So wich changes are made to the sysNAND? And how can I reverse those made changes? 

Same goes for HWClock changes.

Maybe someone add an references for the applied changes to the NAND.

LG

**Comment by d0k3** [comment]
RTC changes change nothing on your SysNAND memory. There are changes on any homemenu boot, though.

The essential.exefs on your SD card is actually only a backup of a backup. The 'main backup' resides on your SysNAND in some otherwise unused - and never touched by the system memory (that's the place where it belongs).

Reverting is not recommended. If you do wish to send it in, restore an older backup or fix it via a script. Or ask around in some scripting thread for help.

**Comment by Maxmeas** [comment]
So maybe it’s possible to add a hint in the prompt, that NAND changes are applied?

**Comment by d0k3** [comment]
That hint is already there.
