### ISSUE TITLE
No Scripts Option In Home Menu

### ISSUE THREAD

**Issue by lachlanmcnicol** [d0k3/GodMode9#296]
When I press the home button in order to execute a script, there isn't the option available.

![img20180116104219 1](https://user-images.githubusercontent.com/35472283/34966393-3e269774-faab-11e7-940f-9c7e8392669a.jpg)

![img20180116104208 1](https://user-images.githubusercontent.com/35472283/34966434-8213aa58-faab-11e7-94ca-6ed4888248bb.jpg)

**Comment by lachlanmcnicol** [comment]
Yes. It seems like GodMode9 is on version 1.2.1 despite downloading the latest version right from the GitHub page. How do I fix this?

**Comment by ihaveamac** [comment]
make sure you replaced the right file, and are booting the right file, because it seems like you didn't

**Comment by lachlanmcnicol** [comment]
I put the .firm file in /luma/payloads/ and the script I want to run in /gm9/scripts

**Comment by lachlanmcnicol** [comment]
![2018-01-16 11_47_56-e_ - windirstat](https://user-images.githubusercontent.com/35472283/34967504-3c60ab70-fab3-11e7-8b9f-9dc34e29f58e.png)

Here's my file tree structure.

**Comment by james-d-elliott** [comment]
Does GM9 boot the moment you turn it on or do you have to hold a button? If it boots the moment you turn it on GM9 is in the root of your SD as well. Probably as boot.firm which should be replaced with Luma3DS's one.

**Comment by lachlanmcnicol** [comment]
I boot it by holding power + start

**Comment by SirNapkin1334** [comment]
Try building from the newest commit.

**Comment by james-d-elliott** [comment]
This seems like a troubleshooting thing, may be easier to handle on the Discord chat. 

https://discord.gg/C29hYvh

Otherwise this may help:

Determine the boot method; either a9lh or b9s, if it's b9s then you should have boot.firm on the root. If it's a9lh it should be arm9loaderhax.bin on the root. By the screenshot it looks like you don't have boot.firm so it's probably loading from the SYSNAND explaining the out of date version. To fix this just place boot.firm from Luma3DS release into the root of your SD. I'm 90% sure this is your issue.

**Comment by lachlanmcnicol** [comment]
I got it to work!

I got into the Luma3DS configuration screen and turned on loading from external .firm files (not sure if that helped but anyway) then rebooted into GM9 v1.5.1. Thanks a lot, James!

**Comment by Derek1199** [comment]
@lachlanmcnicol what is your Luma version? Also are you using A9LH or B9S?
