### ISSUE TITLE
Bootloader:Support more locations for `boot.firm`.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#329]
`3:/boot.firm`:The camera provided by the OS stores the pictures on the SD card by default, and this partition is almost never used.
`5:/boot.firm`:TWLN on EMUNAND is not used, so it is safe to store things there.
`6:/boot.firm`:As the first one, this partition is never used.
I think all you need to do is to change [this line](https://github.com/d0k3/GodMode9/blob/4040c716506f681a5f5f6ca3bc3b4f605b796c01/arm9/source/godmode.c#L32).

**Comment by SirNapkin1334** [comment]
Interesting idea, but not all FIRMs support loading from those locations (Luma is a good example). Attempting to load Luma from say, the bonus drive (8:) will cause a crash, displaying the following error:
`Error: Booted from unsupported location: '8'.`
I'm quite sure that loading from 3: will not work (I'll test it though), but 5: and 6: loading may work, since they are stored in the SD card. I'll look into booting firms from there when I get home.

**Comment by d0k3** [comment]
@pthfdr-42 / @SirNapkin1334 - you can boot firms from all these locations. As @SirNapkin1334 said, some FIRMs don't like to be booted from anywhere else but the SD (`0:/`) or CTRNAND (`1:/`).

Now, if I added other bootloader autoboot locations, that would slow down the boot, cause we'd have to check each and everyone of these locations for a bootable firm. It wouldn't be too bad, but the question remains - is that worth the possible advantage of having more `boot.firm` locations? I'd say it isn't, cause either the SD or CTRNAND should be fine.

You could have a look at fastboot3ds, though, for a more customizable boot (yes, TWLP is possible, too).

Closing this now because of the mentioned reasons.
