### ISSUE TITLE
Bootloader:Support for old (A9LH) ".BIN" payloads.

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#330]
You should implement compatibility for old-style ARM9 ".BIN" payloads, for example, the Gateway ARM9 loader.
GW is still relevant nowadays because of direct ".3DS"/".3DZ" ROM loading and an easier-to-use cheat engine.

**Comment by Wolfvak** [comment]
No.

Machine-code images (aka a9lh payloads/binaries) are to be considered deprecated and not used simply due to the headaches they cause due to a variety of reasons (including but not limited to screen initialization, cache state, CPU entrypoints, TCM setup on ARM9, interrupt controller state, messy relocation, etc).

GM9 [used to have](https://github.com/d0k3/GodMode9/commit/af32ca3ac55580d43ee02b1f8798b62a7234487a) a bootloader for such binaries since people found it desirable and they were still used regularly, but it has since been phased out.

If GW was relevant nowadays, someone would make a FIRM wrapper for their ARM9 loader anyway.
All I know is that people have tried and it's quite messy (their loader has a bunch of shitty obfuscation mechanisms that make it annoying to work with).
