### ISSUE TITLE
Feature request:File-based backup

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#331]
Instead of dumping the whole NAND, it is a better idea to copy the files from NAND partitions and only dump necessary data (like FIRMs and encryption-related data).Thay way, the backup size should be smaller, compresses better, and directly accessible on a PC.

**Comment by Wolfvak** [comment]
NAND backups are done this way so they can later be fully restored with a hardmod, in case your NAND header goes bad for some reason or your FAT (rather than your files) becomes corrupted, spontaneously combusts, etc.

If you want a "quick backup" mode you can use the essential files backup, since they contain your console unique files.

**Comment by SirNapkin1334** [comment]
Perhaps somebody will make a "quick" NAND backup script. If we ever see file compression support, we could copy all the files to a compressed archive.

**Comment by d0k3** [comment]
@pthfdr-42 - this is actually not a bad idea. Main problem: such a backup won't help you if your NAND is seriously borked. Such a backup expects at least the basics partition structure (MBRs, FATs, even the NCCH header and the secret sector) to be proper.

I think this is rather something that should be handled by a script (once we got ZIP compression support, ofc). ZIP support *is* planned, so you may ask around in some scripting thread or the GM9 Discord channel later.

Closing this now.
