### ISSUE TITLE
Unlock Write Permissions Sequence Not Documented

### ISSUE THREAD

**Issue by MKWPlayer1337** [d0k3/GodMode9#35]
Hello. In the readme, the way to increase permission levels are not documented, or the sequence is not posted on how to do it. Can someone please help me on how to unlock the write permissions? I know what I am doing, plus I have had a lot of experience in the 3DS hacking community, so no need to worry about breaking the system. All I want to do is to delete a file called "essential.exefs" I accidentally created while trying to get used to GodMode9.

**Comment by ihaveamac** [comment]
if you attempt to modify something that requires these write permissions, it should prompt to unlock them after. is there a case where it doesn't?

**Comment by MKWPlayer1337** [comment]
I don't know.. It's weird cuz wherever I press R+Y, nothing happens. Plus I am using the latest version of GodMode9...

**Comment by d0k3** [comment]
You can't delete virtual files. Not possible. The essential.exefs file is created by updating the essential backup inside a NAND, it resides on NAND, and because the NAND doesn't have an actual filesystem (but rather a help construct I created), standard FAT operations like delete / rename / move don't work.

I'd recommend leaving that file in there. It's a backup of your most important, console unique files, and it might come in handy later. If you really want to get rid of it, though, overwrite it with an all zero file of the same size.
