### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by YYoshi241** [d0k3/GodMode9#353]
This is basically me rambling on ideas for GM9. I don't care if these are added :)
BCSTM to WAV converter
reduces the annoyance of dump then converting the file on PC.

ZIP file explorer
because it doesn't support zip, yet (neither does CTRXplorer) maybe 7z/rar too...

(Don't know if possible) Change brightness to 3D slider as an option
I know people complain about this but don't always want to mess with the MAKEFILE
(comment if you know if this is possible; if it isn't, ignore this)

Mount 3DSX files
(this may be controversial as some may want to keep the code secret.)
because this is the only major 3ds file (that I can think of) that isn't supported

**Comment by QCFium** [comment]
> (Don't know if possible) Change brightness to 3D slider as an option
I know people complain about this but don't always want to mess with the MAKEFILE
(comment if you know if this is possible; if it isn't, ignore this)

It's possible.
But is there meaning to use the 3D slider instead of the volume one ?

**Comment by YYoshi241** [comment]
I said why in the post :)

**Comment by Wolfvak** [comment]
>BCSTM to WAV converter
reduces the annoyance of dump then converting the file on PC.

That's insane and would be pretty slow on the 3DS. It simply has no place on GM9.


> ZIP file explorer
because it doesn't support zip, yet (neither does CTRXplorer) maybe 7z/rar too...

I think ZIP is already being looked into, although random access would be impossible/take a ton of memory.


>(Don't know if possible) Change brightness to 3D slider as an option
I know people complain about this but don't always want to mess with the MAKEFILE
(comment if you know if this is possible; if it isn't, ignore this)

It is possible, but then you lose compatibility with (n)2DS systems. Sure, you could make it so that 3DS users use the 3D slider and 2DS users keep the volume slider, but then it becomes a mess really quickly.
The alternative would be to read it from a configuration file, but until such thing is made, there's no other way.

**Comment by YYoshi241** [comment]
I understand what you said. Remember that I said I don't really care about these features, I just wanted to put them out there.

**Comment by QCFium** [comment]
I meant, what is the actual difference between the volume one and the 3D one?

**Comment by SirNapkin1334** [comment]
Zip is planned, but as for the other ones, repeating what Wolfvak said, probably not for various reasons.
About mounting 3DSX files... it could probably be possible, but would it be useful? There’s a difference between mounting and decompiling. And, also, which do you mean? The only closed-source project in .3dsx form is Themely, which has an open-source variant and (iirc) isn’t even continued/useful.

**Comment by YYoshi241** [comment]
2 reasons for 3d slider
on o3ds volume slider is on the side and is often bumped and some people dislike blaring music from their home menu when they leave GM9.

**Comment by QCFium** [comment]
Ah, the second one is the same for me.

**Comment by SirNapkin1334** [comment]
What about those on a 2DS? What if they want to adjust brightness? They'd have to implement checks for it which, while not too difficult, are likely unnecessarily complicated. Plus, what if you don't want to be instantly greeted by 3D as soon as you boot? What if your 3D slider is broken? (I have an o3DS with a broken 3D slider). Both have their advantages and disadvantages, but Volume Slider is probably the best. (Can we even access the 3D slider position on arm9?)

**Comment by ihaveamac** [comment]
that's why it would likely be a compile-time option.

**Comment by SirNapkin1334** [comment]
Good idea. If you really want to use the 3D slider, you can compile it with a flag. Perhaps `SLIDER=VOLUME` `SLIDER=3D`. The default should be Volume.

**Comment by Wolfvak** [comment]
No, adding more compile time options regarding brightness is a hack, and not a good one.

Someone suggested to use R+DPad Up/Down while on the browser to adjust the brightness, what do you people think about that?

**Comment by d0k3** [comment]
R+DPAD is already taken for all four directions I think. R+up reloads the file listing, R+left/right handles marking file entries.

Anyways, here we have a multi feature request issue, oh well...

* BCSTM to WAV converter - I understand why you want that, but I fully agree with Wolfvak. Won't be implemented.
* Mounting ZIP files - simply not possible, sorry. A ZIP file extractor would be possible, and is up for discussion.
* Brightness slider stuff - seems like the brightness slider is one of the most controversial things in GM9. We'll stick with the volume slider, but a config file for handling this may be coming up.
* 3DSX file mounting - that may be an option, I need to check. You need to keep one thing in mind, tho. The only thing mountable in a .3DSX file is the RomFS, and not all .3DSX files have a RomFS. So, a lot of 3DSX files would still not be mountable.

**Comment by SirNapkin1334** [comment]
Yeah, R+Dpad is taken, though you're remembering them wrong @d0k3.
R+down = reload file listing
R+left/right = switch panes
R+down/up = fast scroll textviewer/hexviewer/file renaming

R+left/right isn't for marking stuff - that's L+up/down
Using R+L+up/down also is taken - R+L is a screenshot.

Also, why can't we mount ZIP files? What makes it impossible? Not that we need it, extracting them is good enough, AFAIK the only OS that can really mount compressed stuff is Windows so it's not like we're missing out on much, especially *nix users.

**Comment by wabberz** [comment]
The issue with mounting ZIP files is random access. That's hard to do without keeping the uncompressed file in memory or on storage temporarily - both of which are unrealistic on 3DS.

And of course you can mount compressed files on *nix systems: https://bitbucket.org/agalanin/fuse-zip/

This is just one example. Mounting any file type is much easier on Linux than it is on Windows...

**Comment by SirNapkin1334** [comment]
Thanks!
Oh, I meant natively.

**Comment by wabberz** [comment]
I don't want to go off-topic too far, but "natively" is the wrong word here. Explorer allows easy access, but you can't work inside a ZIP file like in a normal folder.

Also, Linux is the kernel, which incidentally does support several compression schemes like zlib, lzma, lzo, ... Since there are thousands of Distributions using the Linux kernel, your claim seems a little bold. I would rather compare Windows Explorer with Nautilus, Nemo, Dolphin, Konquerer and whatever else people use as file manager. Some of them certainly do support accessing ZIP files.

The point is, even in Windows Explorer, the ZIP file is not really "mounted", because compressed archives are rarely made for random access in a working environment, but for long-term storage or transmission.

**Comment by d0k3** [comment]
What @wabberz said, entirely correct.

Anyways, the 3DSX mounting thing - doesn't really make sense because not all 3DSX have the RomFS partition (and as I said, the RomFS is the only thing that can actually be mounted). You will also be hard pressed to find a 3DSX that has a RomFS partition and no source code available (that will then also contain the contents of the RomFS).

So... as the RomFS in 3DSX is a little different from what we have in NCCHs, and as support would make the code messy and require considerable effort... I'm only willing to do so if it actually makes sense (ie. if there's a closed source 3DSX with a RomFS, I doubt it).

**Comment by d0k3** [comment]
Okay, to wrap this up... the brightness slider issue will be solved by a proper GM9 config later. ZIP file exploring, the BCSTM to WAV converter and 3dsx mounting have been discussed and won't make it into GM9 (for 3dsx mounting, until there's a good reason to do so).

ZIP extraction (aka, not mounting) is not out of question. If you want this, open a proper feature request for it.
