### ISSUE TITLE
.FON/.PSF fonts support

### ISSUE THREAD

**Issue by pthfdr-42** [d0k3/GodMode9#358]
Sorry for another feature request.
The standard bitmap font format is FON/FNT on Windows and PSF for UNIX-likes.Most sites only provide such formats of bitmap fonts ([example](http://orangetide.com/fonts/DOS/)).Also, they are easier to edit on a PC.

**Comment by d0k3** [comment]
Yeah, `.fon` is a proper bitmap font format, but supporting that in GM9 would mean a lot more effort than it is worth. Add to it that font support in GM9 is limited to the ASCII tables and to fonts of maximum 8x10px. Also, `.ttf` is a lot more common in Windows.

Related info: I tried my hands at a `.fon` to `.pbm` converter once and stopped because of the effort it would require. I'm willing to give some limited help if someone else tries it, but `.fon` support in GM9 is out of question for now.
