### ISSUE TITLE
Restore sysnand issue

### ISSUE THREAD

**Issue by david-zzj** [d0k3/GodMode9#43]
in the 2.1 system，otp.bin has already got，and i use GM9 restored sysnand.bin succeed.
but when i turn on the console，it displayed some issue i had never see before，please help....

![Uploading issue.jpg…]()
 
![Uploading issue.jpg…]()

**Comment by david-zzj** [comment]
an error has occurred：
failed to apply 1 firm patch（es）.
press any button to shutdown.

**Comment by d0k3** [comment]
I have my doubts it is really GM9 that is responsible here. I don't see the screenshots though. I guess your backup is broken. You could try mounting the NAND image, then trying to transfer (in the A button menu...) the CTRNAND instead. May not work, though. Otherwise, seek help in the usual locations (the #3dshacks IRC channel, for example) and **let me know if you get it solved**.

**Comment by david-zzj** [comment]
i used GM9 to transfer a 11.2 CTRNAND is work.
all goes correct.
THX！！！
