### ISSUE TITLE
[Feature Request] Add option to check for corruption of 3DS System Title

### ISSUE THREAD

**Issue by the4anoni** [d0k3/GodMode9#451]
Hello
Like in topic - please add option to easy check missing system titles/files/etc

**Comment by d0k3** [comment]
Might sound good on paper, but getting this right would be near impossible. You know there are 30+ different FW versions, each with several region variants? Multiply that by the number of important titles / files, and you know what you'll get yourself into. Also, don't forget there are several formats which are not fully understood (ticket.db, title.db, ...).

GM9 already has the ability to verify titles, and it can do so in batch. You can even write a script to do a simple system check (I can add a `chkcmac` command if that helps). The simplest way to check if something is wrong is trying to boot it, though - then you'll see. You can then proceed getting help from somewhere (GBAtemp, f.e.) to try and fix it.

*If* this is about a specific problem, I suggest you ask for help on GBAtemp or IRC. You can point me to your thread and I'll chime in, too. Otherwise, such a feature is not really feasible.
