### ISSUE TITLE
Game cart empty

### ISSUE THREAD

**Issue by Voltaius** [d0k3/GodMode9#510]
I wanted to copy Ultra Moon to gm9, but the game cart said it was empty. When I tried to copy, it failed, saying there is not enough space. However, I know for certain that I have enough space on the SD card because it is a 16gb card. After it fails, the game cart doesn't say empty anymore, and instead has "(CTR9002FOC2)" after it. Initially the empty game cart said 3.4GB but now it says 4.0GB.  When I try to copy again, it still fails saying there is not enough space. The decryption also fails. I don't understand why it won't let me do this. It shows empty for other games as well, but the games all show up on the home menu. Am I supposed to have the game fully updated? It says an update is required on the home screen, but I didn't know if this matters or not.

**Comment by TurdPooCharger** [comment]
1. Copy everything off your SD card over to a computer.
2. Reformat the card in FAT32 +32 KB cluster size using Windows File Explorer or [guiformat](http://www.ridgecrop.demon.co.uk/index.htm?guiformat.htm).
3. Full Write + Verify the empty card with [H2testw](https://3ds.hacks.guide/h2testw-(windows).html). Test the card for hardware defects and whether it is fake.

Report back your scan results.

**Comment by Voltaius** [comment]
Alright, currently, trying this, it's taking a while to copy everything but I will report back with results after.

Also, in disk management, the sd card says 0% space available, if that is of any use.

**Comment by Voltaius** [comment]
May I ask how to reformat the card that way? I know it's already a FAT32, but I don't know how to add the +32 KB cluster size.

**Comment by Voltaius** [comment]
Also, when I complete formatting, is it safe to copy and paste everything back to the SD card without going through the entire process of getting the custom firmware?

**Comment by TurdPooCharger** [comment]
For Windows File Explorer, you right mouse click the letter drive → **Format...**:
- **File system:** FAT32
- **Allocation unit size:** 32 kilobytes

For cards bigger than 32 GB, you have use guiformat.
- **Allocation unit size:** 32768

No copying and pasting anything until _after_ the emptied out card has been tested and passed with H2testw.

**Comment by Voltaius** [comment]
After formatting the card like you said, when I go to test it in the link provided, it says "all available space (15265 MByte)". Is it supposed to show this?

**Comment by TurdPooCharger** [comment]
For H2testw, all available space → Write + Verify.

**Comment by Voltaius** [comment]
It says it is testing 15265 MB of 15266,  but all available space says 15265. Is this an error of some sort?

**Comment by TurdPooCharger** [comment]
That's fine. Sometimes depending on the program, reformatting a card sets aside a 1 MB partition reserved for system volume and cache stuff.

**Comment by Voltaius** [comment]
The reason I'm doing this is because I want to randomize my game, so when I dump my game and randomize it, is it possible to put it back on the 3ds to play from there, or do I have to play from the computer?

**Comment by Voltaius** [comment]
Okay, the test finished. This is what it said:
Warning: Only 15265 of 15266 MByte tested.
Test finished without errors.
You can now delete the test files *.h2w or verify them again.
Writing speed: 15.8 MByte/s
Reading speed: 18.0 MByte/s
H2testw v1.4

**Comment by TurdPooCharger** [comment]
Okay, so your card tested good. Yes, delete the *.h2w test files. Leave open 5 GB of free space when trying to dump that Ultra Moon 3DS rom.
- [Dumping a Game Cartridge](https://3ds.hacks.guide/godmode9-usage.html)

Because the FAT32 format only allows for files slightly less than 4 GB in size (precisely 4,294,967,294 bytes or 2 bytes smaller than 4 GB), you might not be able to dump the full size rom.

You'll have to copy and paste `[TitleID].trim.3ds`.

Check if GodMode9 still doesn't allow you to dump the trimmed version of the game. If you have another game cart, try dumping that too before it can ruled out if your physical copy of Ultra Moon is at fault, or there's something wrong with this homebrew app.

***

By the way, the GitHub issues page is meant to report software bugs found in GodMode9 or request for added features. To ask for help randomizing your game, check out:
- [[GBAtemp.net] 3DS - ROM Hacking, Translations and Utilities](https://gbatemp.net/forums/3ds-rom-hacking-translations-and-utilities.276/)
- [[discordapp.com] Nintendo Homebrew Channel](https://discordapp.com/channels/196618637950451712/196635695958196224)

**Comment by Voltaius** [comment]
Okay thank you. Can I safely copy and paste everything back into the SD card?

**Comment by TurdPooCharger** [comment]
Yes, it's safe to do so knowing now that your card is reliable and working as expected. If dumping the cart's rom proves problematic despite having the available free space, also see if the game can be dumped on another 2DS/3DS if you have another system in your possession.

**Comment by Voltaius** [comment]
I don't have another 3ds, but it works on a regular 2ds? I have a 2ds lite, would that work? Would I just put the sd card in the 2ds just as I would for the 3ds?

**Comment by TurdPooCharger** [comment]
You dump the rom in question on another system in other to rule out whether your 2DS has a faulty SD card slot reader and/or game cart reader, or that copy of your Ultra Moon is borked (failed flash memory corrupted its .3ds rom image).

**Comment by Voltaius** [comment]
When I tried copying the files back over to the newly formatted SD card, it said:
"964 MB is needed to copy these files. 16GB SD is full. Please insert a new storage device to continue copying these files."
I just formatted it, how is it full? This is just like before, when I check the device management in the command prompt and from disk manager. It said 0% free 0 MB remaining. What am I supposed to do?

**Comment by TurdPooCharger** [comment]
Woah woah woah.. Let's roll back about the lack of available free space on your SD card. 

Not to antagonize you, but are you new to using computers and storage medias such like hard drives, USB flash drives, and SD cards?

Apologies if this may seem out of place to ask, but do you know whether or not the entirety of your data/files totals the max capacity of your 16 GB card? Do you know for sure / expecting that the amount of data you're using is much less than 16 GB? 

If the idea of data seems abstract, think of the impossibility of pouring 1 gallon of water into a 1 cup container.

**Comment by Voltaius** [comment]
I have experience with storage medians, and now I feel quite ignorant about this... The files all total to about 14 or so GB, which is obviously why the storage was a problem...
But how am I supposed to fix this? I just followed a Youtube video online about installing custom firmware and copied it. This worked, but I didn't know it would be too much space for the SD card.

**Comment by Voltaius** [comment]
Okay, it's working now. The problem was during the installation of the custom firmware, I accidentally deleted some files but had to back it up. However, the file history feature of Windows 10 was being a pain and kept putting the files backed up into the SD card. It's working now! Thank you for all of your time and help.

**Comment by TurdPooCharger** [comment]
Oh, about hacking the 3DS with custom firmware. The go to resource is:
- [3ds.hacks.guide](https://3ds.hacks.guide/)
Try not to rely on video tutorials due to outdated info that can brick your system or cause improper setup.

As for your main issue, the reason GodMode9 can't dump your rom is well... your SD card ran out of free space. Upgrade to a bigger capacity card if you intend to expand your 3DS library.

Remember to test all your newly purchased SD cards with H2testw to protect yourself from fraud.

If you need further assistance with other 3DS related problems, come check out:

- [3DS NOOB PARADISE - Ask questions here](https://gbatemp.net/threads/3ds-noob-paradise-ask-questions-here.359035/)

**Comment by Voltaius** [comment]
Yeah, it's currently dumping right now. There was enough space in the SD card with custom firmware installed, I just messed up trying to retrieve lost files. It seems fixed now though.

**Comment by Wolfvak** [comment]
Will close this - it seems the issue was fixed.
