### ISSUE TITLE
Can't build CIA from 3DS file: "Build failed"

### ISSUE THREAD

**Issue by stargazingx13** [d0k3/GodMode9#522]
Hi guys! I'm running into a kind of unfortunate error.

I have some Citra decrypted 3DS files that I wanted to convert into CIA files. Altogether, they're 10GB (300MB-1.7GB per file), and my SD card has 11.6GB of space. Attempting to convert any of the files leads to an **immediate** error of the build failing. There's no error code, no explanation, and it doesn't work with any of the files.

I used both the native GM9 options, and the GM9Megascript to attempt to convert them. Nothing worked. As well, decrypting, encrypting, verifying, etc, also do not work.

**Comment by Validusername16** [comment]
From things I have seen in the past, this is an issue with using pirated content, which is bad and you should feel bad.

**Comment by stargazingx13** [comment]
Yeah honestly, you're probably right. I managed to find my copy of Animal Crossing anyway (the only game I wanted to recover, but I got carried away...), which I successfully built into a CIA and put into my system.

**Comment by TurdPooCharger** [comment]
@stargazingx13, ignore @Validusername16's unhelpful advice.

You may want to check if your SD card is fake. Copy everything off it, reformat in FAT32 + 32 KB cluster size, and full Write + Verify in [H2testw](https://3ds.hacks.guide/h2testw-(windows).html).

Other than bad checksum (ie, roms are not intact), GodMode9 will not convert if you don't have enough free space.

You can also convert 3DS roms to CIAs on desktop using [3dsconv](https://github.com/ihaveamac/3dsconv/releases).

**Comment by Validusername16** [comment]
In most cases, “Decrypted .3DS files” are poorly pirated content that as you say, has a bad checksum. Works in Citra but will immediately fail at encryption using GodMode9 or similar tools.

**Comment by stargazingx13** [comment]
@TurdPooCharger No, @Validusername16 is right. I went to a website to find an Animal Crossing file, found a lot of files for games I've owned in the past, and went absolutely nuts. Hearing him say that kind of made me realize my mistake.

The SD card's not fake, I bought it myself, and it converts every game cart I've owned without fail. So, when I found my game cart, there's really no point in keeping the unworking files, and I should work on finding them, instead.

Thus, I don't see a reason this should be open, because I shouldn't be encouraging piracy. I was desperate, and I apologize.

**Comment by TurdPooCharger** [comment]
@stargaizingx13, to safe guard your data, you should test your SD card anyhow. It's a good time to check since you've never done so. If it's not fake, it could be dying. A bad or failing card will corrupt your files with continual use.

Those 3DS roms may in fact be good dumps that might have possibly be affected by a faulty card. This all depends if whoever leaked them in the first place did their due diligence uploading intact dumps.

Romhacks such as the Pokemon series are another matter. These don't necessarily have matching checksum and often times cannot be installed on the SD card unless you start from scratch with Luma LayeredFS patching (if the mod is available).
