### ISSUE TITLE
Feature Request - Create and extract compressed archives

### ISSUE THREAD

**Issue by ahoischen** [d0k3/GodMode9#53]
There are currently no methods of creating or extracting compressed archives on the 3ds. This is a problem, since the typical method of transferring files to the 3ds, FTP, suffers from *terrible* transfer rates for large collections of small files. Implementing this feature might also encourage users to do more frequent backups because they don't take up as much space on their device anymore. Since archive managers benefit hugely from being able to explore their filesystem and that of the device, it seems reasonable to request for GodMode9 to include this feature.

Should this feature be implemented, the `zip` compression format would be a minimum requirement due to its prevalence. Supporting other formats (.tar.gz, .7z, .rar) is optional but appreciated.

For implementation, I suggest [libarchive](https://github.com/libarchive/libarchive) which supports a wide range of formats; however, I have not yet tested its compatibility with the 3ds.

**Comment by d0k3** [comment]
Noted, and I like the idea. However, this is not easy to implement, so it might take a long time to make it's way into GodMode9.

As for your idea of also compressing backups - there are more complications with that than you accounted for. Have you ever tried compressing a NAND backup? These compress pretty badly, due to encryption. Even decrypted ones compress badly, because of unused sectors (these are all zeroes on NAND) being decrypted to a badly compressible state.

**Comment by ahoischen** [comment]
Oh, you're right I forgot about the encryption. Thanks for pointing out my error and accepting the idea. Since this isn't a pressing issue I can understand if other features and fixes take precedence.

**Comment by WubTheGame** [comment]
i like this idea, i would love to be able to open archives straight from my 3DS.

**Comment by BARNWEY** [comment]
Please do this!

**Comment by d0k3** [comment]
After thorough consideration, I decided to not have this in GodMode9. While it may be useful occasionally, it is a massive pita to implement and simply not worth the effort for what use it may have. Closing this now.
