### ISSUE TITLE
Suddenly quitting the mounting of 'ticket.db' crashes hourly build v1.8.0-77.

### ISSUE THREAD

**Issue by TurdPooCharger** [d0k3/GodMode9#532]
**Procedure**
1. **[1:] SYSNAND CTRNAND/dbs/**`ticket.db` → **Ticket.db options...** → **Mount image to drive**.
2. Immediately press and hold the (B) button to try to cancel.

***

**GodMode9 v1.8.0 (stable)**
- Mounting image: failed

***

**GodMode9 v1.8.0-77-g65c605f5**
- [exception_dump_010122143705.txt](https://github.com/d0k3/GodMode9/files/3587437/exception_dump_010122143705.txt)

<img width="450" alt="ticket db failure" src="https://user-images.githubusercontent.com/35666439/64485920-5e8c7700-d1f4-11e9-8c82-d7cabbecf158.png">

**Comment by d0k3** [comment]
Fixed by @aspargas2, thank you! @TurdPooCharger - please test.

**Comment by TurdPooCharger** [comment]
Late reply due to never getting a working devkitarm setup until recently. The hourly build with this commit no longer crashes when quickly dismounting  the `ticket.db`. 

Visible now are the drive and file **[D:] DISA/DIFF IMAGE/**`partitionA.bin`, from pull request # 509?

**Comment by d0k3** [comment]
Uhm... what do you mean?

**Comment by TurdPooCharger** [comment]
If you allow `ticket.db` to load, it will bring up **[T:] TICKET.DB IMAGE**. However, if you mount and then press + hold (B) to cancel, it'll instead bring you to **[D:] DISA/DIFF IMAGE**. 

This new drive comes from @aspargas2 work in pull request # 509 - DISA/DIFF writing and title database inner FAT support.

**Comment by aspargas2** [comment]
Yeah, that's because my code tries to tell the old vtickdb code to also mount the image as a virtual drive whenever it sees a diff file. This immediately fails if the TICK magic isn't found, which is what happens when mounting and diff file that's not a ticket database, meaning my code ignores the return value of vtickdb initialization. Therefore, if vtickdb initialization fails for any other reason, like the user canceling the scanning, my code will have still already mounted the image successfully. Godmode.c is what handles the drive that gets entered after mounting, and currently T: is higher priority than D:, which was intentional on my part.
So, with all that said, I don't see anything wrong with that behavior.
