### ISSUE TITLE
SaltMode Boot Menu is broken in Staging Build (186dd368)

### ISSUE THREAD

**Issue by Kalanyr** [d0k3/GodMode9#540]
The current staging build ( https://github.com/d0k3/GodMode9/commit/186dde68cfe26dced023cc012f8dbbe4c0fa1048 )  in SaltMode works as a pass through bootloader (ie it will start boot.firm)  but if you hold down the Start button to go into the bootloader menu it hangs perpetually on this screen: 
![LoadHang2](https://user-images.githubusercontent.com/5610991/64792825-5f8b2300-d5bd-11e9-942b-e9df7d85a5d9.png) (This picture is old (hence the old build number) but the current situation is exactly the same and  I don't really want to have to retake the picture with my phone) 

If however you boot the firm from within a functioning GodMode9 bootloader, it enters into GodMode9 normally, so this appears to be an issue with the bootloader specific code. 

(The current SaltMode9 from the website instead doesn't act as a passthrough bootloader and boots into GodMode9 every time but I believe that's known.). 

Reposted as  a separate issue as requested on ( https://github.com/d0k3/GodMode9/issues/514#issuecomment-533919025 )  as problem still exists on the current staging build.

**Comment by Wolfvak** [comment]
Found the problem, I think it's caused by a messed up `HID_ReadState` call not taking into account the new shell open/closed status bits...

Can you test this new build?
[GM9-boot-anybtn.zip](https://github.com/d0k3/GodMode9/files/3667438/GM9-boot-anybtn.zip)

**Comment by Kalanyr** [comment]
Still seems broken but differently. Holding down Start on boot mostly seems to make the console shutdown most of the time. 

 I'm pretty sure I saw it go into the menu , then into GodMode9 and then restart once realllly quickly but I wouldn't swear to it. I think it booted into GodMode9 directly once but that was on the first restart after I'd installed it and I was doing a hot reboot. 

In terms of stuff I can reproduce just go with the first one. I've got no idea what's happening with the rest or if I'm just losing my mind. 

It also seems to cause a known working GodMode9 build (in SaltMode) to not boot even using Luma's bootloader. This I can reproduce. It just causes a shutdown.  I'll try a non-SaltMode GodMode9 in a sec and let you know what happens with that. I might need to magnethax this to recover.

**Comment by Wolfvak** [comment]
Ok, having Luma in the bootchain makes reproducing this impossible for me because my system doesn't suffer from this bug. You'll have to either swap Luma out with another bootloader or wait for someone else.

The bug listed here was about the console getting stuck on boot - now it either boots and acts as it should or shuts down instantly, correct? That sounds like the bug was fixed, we just have to figure out how to fix the shutdown...

**Comment by Kalanyr** [comment]
No, it booted fine in passthrough mode (and could use the Luma chainloader) in the current staging build , but hung on trying to enter SaltMode boot menu,  this variant boots fine in passthrough mode (but seems to break the Luma chainloader causing a shutdown) and shuts down rather than anything else when trying to enter the SaltMode boot menu.

**Comment by Kalanyr** [comment]
Okay. I reinstalled Boot9Strap and then used the Luma chain loader to go back to the old working version of SaltMode9 so I can do further testing now.

**Comment by d0k3** [comment]
Okay, here's two test builds for you:
https://f.secretalgorithm.com/NXaEH/godmode9-v1.8.0-101-g0796cdfd-20190930221617.zip
https://f.secretalgorithm.com/4v3lC/saltmode9-v1.8.0-101-g0796cdfd-20190930221923.zip

Both should work perfectly. Can you please test?

**Comment by Kalanyr** [comment]
Certainly.  Just want to confirm that the one labelled god mode should interrupt the bootloader with R + Left rather than Start ?

**Comment by Kalanyr** [comment]
Starting from working SaltMode9 build ( g9ab9c01a)
Both of these work from Luma chainloader
Both of these can be launched after going into GodMode9 from boot holding down Start 

Trying flashed to Firm0:
SaltMode works as a passthrough bootloader. SaltMode works to go into Bootmenu when holding down Start, Luma chainloader still works  (So everything works as expected) 
GodMode  works as a passthrough bootoader, , GodMode does not seem to go into Bootmenu (R + Left and Start both file), the Luma Chainloader isn't broken however so holding down Start boots into that allowing easy recovery.  (So fails to start Bootloader menu, other stuff good)

**Comment by d0k3** [comment]
Okay. That looks a lot like there is some trouble with your buttons. Can you maybe install fastboot3DS and try the boot setup? You can set keycombos there, just see if you're able there to set soemthing to R+left.

Also, there may be some trouble wit hyour build environment. To make sure, can you try compiling from up to date staging (best to do both, SaltMode and standard, and try it as bootloader)? Also be sure to clone fresh, we had a recent force push (had to, normally we try not to do that).

**Comment by Kalanyr** [comment]
My R and Left work individually. I used them in the GodMode while testing
(and I checked them in the Home menu when I had that issue). I'll check the
combo.

I'lll blow my git copy away.

**Comment by d0k3** [comment]
Did you actually try compiling yourself?

One thing you could try, set another boot key (or key combo) here:
https://github.com/d0k3/GodMode9/blob/master/arm9/source/godmode.c#L36
... then compile fresh (non SaltMode).

I still think this is some kind of weird hardware issue.

**Comment by Ammako** [comment]
I'm inclined to believe it's a software issue, rather than a hardware issue.

If I use 9ab9c01 to flash the test build you uploaded above to firm0, I can enter the boot menu with R+Left just fine. But if I use the test build to flash itself to firm0, then I can't enter boot menu, but passthrough works fine.

I can flash b9s firm to both firms using 9ab9c01 and it works fine, but flashing b9s firm to firm0+firm1 using the test build bricks, with black screens. More interestingly, if I flash gm9 to both firms using the test build, it bricks, with a bootrom error. If I flash to both firms using 9ab9c01, everything works fine.

The code for the boot key works fine, but something's definitely wrong with the way the newer builds handle flashing firms.

**Comment by Kalanyr** [comment]
I flashed the GodMode version d0k3 posted with the SaltMode version (but I
flashed the SaltMode from an older SaltMode build I had). So this wouldn't
be inconsistent with my experience.

RE: Question originally asked by d0k3 no I didn't compile my own for these
tests they were done using the builds you posted.

**Comment by Kalanyr** [comment]
Yes, can confirm that Ammako is correct ,I flashed the GodMode9 build d0k3 posted in this thread  using SaltMode version of https://github.com/d0k3/GodMode9/commit/9ab9c01aae1a47ab1ea6ef4567df2f33f381471a . R + Left does cause boot menu entry.

**Comment by d0k3** [comment]
Okay. Thanks a lot, @Ammako and @Kalanyr for being as persisten with that issue as you were. Turns out there was a bad bug in master and staging preventing FIRMs from properly installing.

Here's something to try:
https://f.secretalgorithm.com/pNCId/godmode9-v1.8.0-108-g5799d99c-20191004182807.zip
https://f.secretalgorithm.com/7VX6P/saltmode9-v1.8.0-108-g5799d99c-20191004183052.zip
Both should work as expected with all bugs fixed. You may also compile yourself, the fix is on master. Please test!

**Comment by Ammako** [comment]
Looks good to me.

**Comment by Kalanyr** [comment]
Me too.
