### ISSUE TITLE
Issue with backing up EmuNAND

### ISSUE THREAD

**Issue by arcues19875** [d0k3/GodMode9#542]
Tried backing up EmuNAND with GM9, with enough room on SD Card for backup to be made. SysNAND backed up beforehand worked successfully.

**Comment by Wolfvak** [comment]
Please provide more information.

How exactly does it fail, how are you trying to make the backup, do you have an old3DS or a new3DS, did you check your SD card for defects, etc? Add anything else you think might be important.

**Comment by d0k3** [comment]
@arcues19875 - can't do anything with that bug report as is. How did you try to back up the EmuNAND? Using a script? Manual copy? What exactly happened when it didn't work? What was displayed on screen? Did you check your SD card for trouble?

In essence, what @Wolfvak said. We need more info.

**Comment by TurdPooCharger** [comment]
I'll test GM9 v1.8.0 and the latest hourly build on my o2DS with a spare 4 GB card later.

Testing will be combined with issue #543 to check for **[4:] EMUNAND CTRNAND** and **[B:] EMUNAND SD**.

but I'll report results separately for their respective issues.

**Comment by d0k3** [comment]
Thanks!

**Comment by TurdPooCharger** [comment]
## Setup No. 1
- old 2DS + B9S v1.3
- **4 GB SD card, Class 6** (Kodak brand. Really old: circa year 2009?)
- **Luma3DS v9.1** (fresh GitHub download)
- **GodMode9 v1.8.0** (fresh GitHub download)

I [quadruple reformatted](https://gbatemp.net/threads/new-2ds-xl-microsd-card-error.534480/#post-8569741
) the Kodak SD card and checked it empty in [H2testw](https://3ds.hacks.guide/h2testw-(windows).html) (no hardware problems found). These were the files added to the card:
- **sdmc:/gm9/scripts/**`GM9Megascript.gm9`
- **sdmc:/gm9/scripts/**`NANDManager.gm9`
- **sdmc:/luma/payloads/**`GodMode9.firm`
- **sdmc:/luma/payloads/**`GodMode9_dev.firm`
- **sdmc:/**`boot.firm`

The dev version of GM9 was added to avoid experiencing issue # 466.

**Procedure**
1. (HOME) button → **More...** → **SD format menu** → **RedNAND size (min)** → **32KB Clusters**.
2. After the card gets reformatted, I add back those above files.
3. **[S:] SYSNAND VIRTUAL/**`nand_minsize.bin`  → **Calculate SHA-256**.
4. **[E:] EMUNAND VIRTUAL/**`nand_minsize.bin`  → **Calculate SHA-256**.
5. (HOME) button → **Scripts...** → **GM9Megascript** → **Backup Options** → **EmuNAND Backup**.
6. **[0:] SDCARD (GM9SD)/gm9/out/**`<date>_<serial>_emunand_00.bin` → **Calculate SHA-256**.
7. (HOME) button → **Scripts...** → **NANDManager** → **<A> Backup EmuNAND** → **<A> yes**.
8. **[0:] SDCARD (GM9SD)/gm9/out/**`<date>_<serial>_emunand_000.bin` → **Calculate SHA-256**.

**Result 1**
Both scripts dumped the EmuNAND `*.bin` images, and the calculated SHA-256 hashes between the SysNAND, EmuNAND, and both images all match.

I repeat the procedure with:
- (HOME) button → **More...** → **SD format menu** → **GW EmuNAND size (full)** → **32KB Clusters**.

**Result 2**
Again, both scripts dumped the EmuNAND `*.bin` images, and the calculated SHA-256 hashes between the SysNAND, EmuNAND, and both images all match.

***

## Setup No. 2
- new 3DS XL + B9S v1.3
- **4 GB micro SD card, Class 4** (Lexar brand. Came with the n3DSXL when the system was bought brand new.)
- **Luma3DS v10.0.1** (fresh GitHub download)
- **GodMode9 v1.8.0-111-g2372340e** (`20191010200713.zip`, downloaded from issue #543)

I quadruple reformatted the Lexar micro SD card and checked it empty in H2testw (no hardware problems found). These were the files added to the card:
- **sdmc:/gm9/scripts/**`GM9Megascript.gm9` (from v1.8.0-111 hourly)
- **sdmc:/gm9/scripts/**`NANDManager.gm9` (from v1.8.0-111 hourly)
- **sdmc:/luma/payloads/**`GodMode9.firm` (from v1.8.0-111 hourly)
- **sdmc:/**`boot.firm` (Luma v10.0.1)

**Procedure**
1. **SD format menu** → **No EmuNAND** → **Auto**.
2. **SD format menu** → **RedNAND size (min)** → **Auto**.
3. **SD format menu** → **GW EmuNAND size (full)** → **Auto**.
4. Turned off the n3DSXL. Add back those files to the microSD card from computer.
5. Turned on the n3DSXL and hold (START) button. Keep pressing (START) button until the top LCD displayed GM9 banner with washed out colors due to issue # 466. Boot GodMode9 with the washed out color session.
6. **[S:] SYSNAND VIRTUAL/**`nand_minsize.bin`  → **Calculate SHA-256**.
7. **[E:] EMUNAND VIRTUAL/**`nand_minsize.bin`  → **Calculate SHA-256**.
8. **GM9Megascript** → **Backup Options** → **EmuNAND Backup**.
9. **[0:] SDCARD (GM9SD)/gm9/out/**`<date>_<serial>_emunand_00.bin` → **Calculate SHA-256**.
10. **NANDManager** → **<A> Backup EmuNAND** → **<A> yes**.
11. **[0:] SDCARD (GM9SD)/gm9/out/**`<date>_<serial>_emunand_000.bin` → **Calculate SHA-256**.

**Result 3**
Again, the images dumped fine and all hashes match.

***

## Conclusion (TL;DR)
Creating EmuNAND and backing up the EmuNAND `*.bin` image works as intended in both publicly available latest GM9 v1.8.0 and v1.8.0 hourly builds.

@arcues19875, you should probably quad reformat and hardware test your emptied out SD card with h2testw (windows) / f3x (mac) / f3 (linux). Update to the latest GM9 version. Better yet, discontinue using EmuNAND if you're holding onto some dumb Gateway flashcart setup.

**Comment by Wolfvak** [comment]
Ok, since @arcues19875 hasn't replied after almost a week and we've got confirmation that the feature does work as intended, I'll close down this issue.
