### ISSUE TITLE
Speed up text viewer when very long lines are present in the file

### ISSUE THREAD

**Issue by HIDE810** [d0k3/GodMode9#556]
Selecting `Show in Textviewer` with a text file which has a long string in a line, a long delay occurs. This delay time depends on its string length.

[testtext.zip](https://github.com/d0k3/GodMode9/files/3768259/testtext.zip)

**Info about my system**
* n3ds
* GodMode9 v1.9.0 via fastboot3ds

**Comment by Wolfvak** [comment]
That's just strlen being slow, it's an algorithmic problem. I suppose we rewrite the current algorithm to make it faster though...

**Comment by d0k3** [comment]
Okay, I checked the code and this is not an easy one two fix. See, linescrolling in conjunction with wordwrapping is not exactly trivial. Scrolling down is fast. Scrolling up means (internally) going back to the paragraph start (in case of that file, file start), then moving down. That's the only way to get proper wordwrapping throughout with small memory requirements.

The file you provided is a very special case, which doesn't really matter in real world scenarios. If you can provide an actual 'plausible' file for which scrolling is too slow, we may look into it, but otherwise I'm tempted to close this feature request,

**Comment by HIDE810** [comment]
You can reproduce it with some files in CTRNAND.

**e.g. :**
* titleID: 0004001B00018802
* pass: romfs/js/cave.min.js

[video](https://youtu.be/bp2s_wHLd4I)

Certainly this is a special case, but we can't operate gm9 while loading such a file. If It's difficult to fix the delay, could you add cancel option (B button) while loading it?

**Comment by HIDE810** [comment]
Actually it may not always be necessary. I close this.

**Comment by d0k3** [comment]
Well, I thought about it, and this actually deserves some attention. I'll do something about it. Reopening...

**Comment by d0k3** [comment]
Okay, I guess you thought you won't hear back from me @HIDE810 :).

Try this one:
https://f.secretalgorithm.com/G6YvH/godmode9.firm

Yes, there may still be some delay for those large .CSS files, but it's very much usable and worlds apart from everything we had before the last commit.

Please test and let me know your results!

**Comment by HIDE810** [comment]
Wow, it was largely improved! Though using some large files, they have very little delay.
I appreciate your work :). @d0k3
