### ISSUE TITLE
[BUG] Invalid Pokemon sun dump

### ISSUE THREAD

**Issue by Liger0** [d0k3/GodMode9#593]
**So you want to report a bug?**
I tried dumping my retail cartdridge of Pokemon Sun (EU) as an encrypted .3ds file. 
I wanted to make a perfect copy of it (not trimmed) for being able to check its checksum to see if it went good.
After dumping I checked the checksum, but it was different from the supposed legit legit one, which is

CRC32: | 48DA63F5
MD5: | F449F03CB3428F0089897C4AB79943C0
SHA-1: | DAC05F86C033614413F67B65405618B00EA99DCE

for the encrypted .3ds according to the site I always checked for these values that never failed proving true.
I then asked a friend of mine to dump his cartdridge to verify if it's just me, and he also reported that his checksum was different from both the legit one and mine.
The Pokemon sun total size file 4GB, which is the limit of the fat32 partition, so we wondered if this could be a cause.

**Info about your system**
Include this info to make our work easier:
* Console type: New 3ds(XL)
* Bootloader: B9S

**Have you actually read this?**
[Yes] I have read the information above

**Comment by TurdPooCharger** [comment]
I think it's because GodMode9 dumps 4 GB .3ds roms with 1 byte less than exactly 4.00 GB due to the FAT32 format's file size limit. If you add another byte at the end of that dump, should be **FF** or whatever value that matches the surround, you should get the correct hash next time around. Here's [HxD](https://mh-nexus.de/en/hxd/) in case you don't have a hex editor preference.

**Comment by Liger0** [comment]
GM9 reports the file as 3.9 GB, how is it exceeding 4GB exactly? 
Maybe I am confusing between GB and GiB.

**Comment by d0k3** [comment]
@Liger0 - FAT32 (that's the file system on all 3DS SD cards) does not support files of sizes 4.00 **GiB** and up. Therefore I'm forced to leave out the last byte. Copy the file to your PCs hard drive, use a hex editor to add one byte (most likely 0xFF), check it again. It should be fine. Please check this and let us know your result, I'm keeping this open for the time being,

As for your friends dump - many times, there are several revisions of one cart around, and not just one EU (US, JP, ...) cart. Him having a different checksum than you do does not mean GM9 did anything wrong. What's the name your dump, and what's the name of his dump? Is it the same?

**Comment by Liger0** [comment]
You're right, adding FF as last 2 bytes made it correct.
Wouldn't it be possible to include a warning when dumping such 4gb cartdridges?

I'll take the chance to ask if with godmode9 (or anything you're aware of) you can dump the entire cartdridge as one file and/or know at which offset of the entire cartdridge the sav file is stored for games that store the sav in their own cartdridge. Thanks.

**Comment by d0k3** [comment]
We can't put out a warning there by design (or: it would be very, very hacky) - the gamecart is accessed as file system, and all files are equal. Putting out a warning when touching some files would make things very hard.

If you got a cart dumping script, however, you could show a warning there. Other than that, the recommended format for carts that large is split (I understand this is inconvenient).

There are very few "card2" cartridges that store the savegame on the atcual cartridge memory. If you dump such a cart via GodMode9 the save will not be included on purpose - I'm assumung you want a clean dump. However, for these carts, the save will pop up in the drive, and you can grab it from there.

**Comment by Ammako** [comment]
> However, for these carts, the save will pop up in the drive, and you can grab it from there.

Fairly certain this is not supported yet for card2.

**Comment by Liger0** [comment]
If there can't be a warning during the dumping process, maybe inserting it in the readme as a FAQ would be a good move.
