### ISSUE TITLE
[FEATURE REQUEST] Password protection. 

### ISSUE THREAD

**Issue by DaNxCorp** [d0k3/GodMode9#599]
I didn't see any open or closed issue mentioning this, so here it is. Simply what the title says, a password implementation to prevent GM9 usage from unauthorized people.

Pretty useful if you lend your 3DS to one of those kind of children that like to mess around with devices, or other situations where leaving around your 3DS with GM9 in it could mean irreversible NAND damage due to someone playing with the wrong stuff.

It could be implemented as a prompt inviting the user to enter a custom button sequence, similar to the system used to enable write permissions.

**Comment by d0k3** [comment]
While I am not completely against such a feature, I have my doubts about it's usefulness.

First of all: There is no irreversible NAND damage with GM9 - that's impossible. It is however possible to render your system unusable (which is fixable) and/or delete irrecoverable data (saves, maybe purchases). Which brings me directly to the next point: If someone intends to damage your 3DS data, the only way to stop that for sure is not handing that person your 3DS. Keep in mind, also the 3DS system menu allows uninstalling titles.

Also, there is no unentional damage in GM9. Every potentially damaging action gives you warning and forces you to enter a button sequence to confirm. In other words: someone who damages your system via GM9 is willing to do so. I myself know not of a single case of a toddler (or child) doing any damage via the use of GM9.

On the other hand, you can of course make it harder. If that's what you want, why not install fastboot3DS and customize your boot in a way so that GM9 is not reachable via a key on boot (or at least make it a complicated combination)?

As I said, still open for discussion, but not convinced about this feature.

**Comment by d0k3** [comment]
Alright, after some consideration - a feature such as this (stopping a whole software from being loaded) is the job of the bootloader, not the job of the software in question.

A suggestion: Use fastboot3DS and set some complicated key combo as boot combo for GM9. fastboot3DS is also open for feature requests, if that solution doesn't cut it for you.
