### ISSUE TITLE
[BUG] SD Cleanup seems it doesn't delete nothing

### ISSUE THREAD

**Issue by castore123** [d0k3/GodMode9#633]
I followed the guide on 3 different 3DS : O3DS, O3DSXL, N2DSXL and when I reach the point where I have to clean the SD the option works and gives no error, but actually it deletes nothing, or it is supposed to leave files like "browserhax_hblauncher_ropbin_payload.bin", "arm11code.bin", "usm.bin" and they have to be deleted manually?

**Comment by aspargas2** [comment]
The script is doing something; it's just mainly deleting files that you don't have because they're for older methods of installing cfw. The newest browserhax and USM are both relatively new things, so the script hasn't been updated for their files. I'll update it in a bit.

**Comment by castore123** [comment]
thanks for the fast reply
for install it I've to update from newest version of gm9 or can I download only that file?

**Comment by aspargas2** [comment]
Fixed in commit 8e2d1d4. This change won't be in the releases page anywhere until an entirely new release is made. If you want to get the latest megascript at any given time, you can download it from the repository directly at https://github.com/d0k3/GodMode9/raw/master/resources/gm9/scripts/GM9Megascript.gm9 (press ctrl+s if it just displays the script on screen).
