### ISSUE TITLE
Feature Request - TXT reader with UTF-8 support

### ISSUE THREAD

**Issue by MelonGx** [d0k3/GodMode9#64]
If it's difficult to enhance it then feel free to close this issue because it's not necessary for me.

**Comment by d0k3** [comment]
That's actually something I had planned, so I'm leaving this open.

**Comment by WubTheGame** [comment]
Yay! now i won't have to insert my SD back into my computer when i want to edit a Config or something. Also, any chance .ini support will be possible too?

**Comment by d0k3** [comment]
Textviewer added in https://github.com/d0k3/GodMode9/commit/dd2efaedc5b32f1201532f7a0cda092d289f047b

This is ASCII only and will stay that way - UTF-8 is not possible due to no font support and other issues.

Editing capabilities are unlikely, but I'll think about it. Should be better to use a dedicated tool for that.
