### ISSUE TITLE
[FEATURE REQUEST] Blank Dummy Files

### ISSUE THREAD

**Issue by dwain12435** [d0k3/GodMode9#649]
An option should be added to make a blank dummy file. It shouldn't replace the current way of making dummy files, because it would be too slow, but should be added as an extra option.

**Comment by ihaveamac** [comment]
What would this do differently to the current method?

**Comment by d0k3** [comment]
Assuming @dwain12435 wants files that are prefilled with zeroes instead of - like now - random garbage data. Pretty impractical in GM9, cause filling these files on a 3DS takes a lot time, while just creating them takes almost nothing.

Is this what you meant, @dwain12435 ? What would be a use case for this?

**Comment by dwain12435** [comment]
I know that it would take a long time, that's why I said it should be an
additional option that doesn't replace the current method. It would be
useful for creating FAT images that aren't corrupted.

**Comment by Wolfvak** [comment]
FAT images that are full of zeroes are still corrupted. I'm pretty sure there's no format in the world where zero-data is considered useful (other than maybe plaintext), so this is not a valid argument.

**Comment by dwain12435** [comment]
I meant the ability to make a large blank file to add a FAT header to so
that you can have a functional FAT image. If you add a FAT header to a
large file that isn't blank, then you will have a corrupted FAT image.
