### ISSUE TITLE
3DS Serial "U" sales region

### ISSUE THREAD

**Issue by luigoalma** [d0k3/GodMode9#658]
There are consoles with an `U` on their serial number, the second letter, that appear to be UK consoles.
At least from consoles brought from the store directly.

I've asked someone on the UK, only their store brought console has `U`.
Their online purchased consoles came with `E`, so those could've been sourced elsewhere in Europe.
Adding this piece of information for anyone going out doing further investigation is aware of that online purchased consoles could be sourced elsewhere.

I encountered a `SUF` and a `SUH`.

If we can confirm it to be UK, we could add `U` as `United Kingdom` to the sales region info for system info screen.

Not opening this as a bug report nor a feature request. This is more of a reminder and something that needs some further investigation

**Comment by d0k3** [comment]
I added "U" -> "UK" as a sales region in the system info thing. This is most likely correct, as "U" is not for "USA" (confirmed) and as there's already one confirmed example of a "U" console in the United Kingdom. If this turns out to be wrong, we will correct it later. Apparently there is no comprehensive list of sales region anywhere.
