### ISSUE TITLE
Feature Request - Signature Verification

### ISSUE THREAD

**Issue by Thealexbarney** [d0k3/GodMode9#67]
I assume the current "verify" option verifies the hashes in the 3DS file formats. It might be useful if there were an option to verify the signatures as well.

**Comment by d0k3** [comment]
Not possible at the moment, because we can't handle the RSA hardware. Maybe later.

**Comment by d0k3** [comment]
Okay, pretty late, but we finally have the ability to check signatures. I'm already doing it to eliminate bad tickets when mounting or creating an `encTitlekeys.bin` - it makes sense there. Question is, where else does it make sense? .3ds (NCSD) or .app (NCCH) are questionable, cause a signature check would edit false for any homebrew and any otherwise properly edited files.

**Comment by d0k3** [comment]
Nope, not possible. We actually need a lot more than a working signature verificator to check for sighax. The effort this would require is in no relation to the possible gain. Besides, GM9 does not need that. The installer handles the sighax signature injection.

**Comment by Thealexbarney** [comment]
That's great news. Nice work. I think it would make sense to be able to check the signatures on whatever metadata there is for installed titles. (Is the signed TMD installed to NAND?) That way users could verify that an installed title is unmodified.

**Comment by d0k3** [comment]
@Thealexbarney - Yes, the TMD is installed to NAND, but it is somewhat not used by homemenu. Remember H&S injection? That only worked cause the TMD SHAs are never checked after installation.

So, we'd need to check signature, then reencrypt and check SHAs (cause SHAs are for encrypted contents). That will take a shitton of effort on my side and a shitton of time (~10 minutes for a title of 1GB), enough so that no one will ever want to use that feature. Not really a good idea.

What could make sense is checking the signatures of cartridge NCDs (aka as .3ds files). That way some limited checking of validity could be done (also not complete, cause we cannot check the RomFS SHAs of the contents). Problem here: We don't have the public keys for that.

**Comment by d0k3** [comment]
Alright, after nothing new popped up, and after I explained why sigantures may not be as useful as everyone thought, I'm closing this.

We do have signature handling now, we just lack some of the public keys and the usefulness outside of ticket validation is doubtful at best. Feel free to get back if you got any other ideas.
