### ISSUE TITLE
[HELP WANTED/TESTING] Proper display of japanese characters (unicode support ?)

### ISSUE THREAD

**Issue by TheShadowRunner** [d0k3/GodMode9#687]
Hi and congratulations on release 2.0 !
I would like to request proper japanese font diplay for titles.
Currently japanese is rendered as "???????" as can be seen on this sample image:
![Dsc_0060](https://user-images.githubusercontent.com/1895340/112196695-94912080-8c0b-11eb-9945-d8c990c9d2fe.jpg)
Thank you for considering !

**Comment by Mewthree3** [comment]
I'd like this as well

**Comment by d0k3** [comment]
Not against it. But we will need a japanese font in pbm format and proper adressing, and there's no way I'll be able to do this on my own. A 6x10 japanese font may also be a little hard to do.

Anyways, if someone can do the font and someone knowledgeable in unicode can help with the adressing, we can add that.

**Comment by d0k3** [comment]
Alright, thanks to @Epicpkmn11 (big thanks for that, again) we now got Unicode support in GodMode9. You can even enter Unicode symbols via the software keyboard hex numpad, and you can create your own Unicode fonts.

What we need now, is testing, and we basically need testing for everything, but especially for everything that's in any way connected to text. Counting on your help here!

Here's a test build:
[GodMode9-v2.0.0-34-ge1e0e6fb-20210831135031.zip](https://github.com/d0k3/GodMode9/files/7083628/GodMode9-v2.0.0-34-ge1e0e6fb-20210831135031.zip)

**Comment by Mewthree3** [comment]
On Thursday/Friday I’ll download the build! I’m really happy for Japanese support! Great work⚡️

**Comment by TheShadowRunner** [comment]
Thank you very much for your work @Epicpkmn11 , we're almost there!
As you can see on the pic there are still quite a few missing characters, I'm guessing they're all kanjis ?
At least we got hira & kata which helps a LOT already! ^^
![Dsc_0081](https://user-images.githubusercontent.com/1895340/131725464-386dc196-04eb-46cf-b62e-a8f348516075.jpg)

**Comment by TheShadowRunner** [comment]
Thanks!
So I guess I have to grab these 3 files:
https://github.com/Epicpkmn11/GodMode9/commit/68a1a5082ebe24fc736ae46238a5b4597c1d7a4e
and create a resources/fonts folder at root of SD card?

**Comment by TheShadowRunner** [comment]
Oh that's how it works ^^;
Thank you again.

**Comment by TheShadowRunner** [comment]
Epicpkmn11, is it possible for you to make a font that has standard latin characters (same size and spacing as GM9 default) but that has also full jpn support (kanjis) ?
Frankly 8x8 美咲ゴシック doesn't look too good and kanjis are still hardly readable.
Even if kanjis are even harder to read at 6x8, it's still better than question marks of the default font, and latin would look ok.
What I'm looking for really is the default font with kanjis support even if they don't look too good.

**Comment by Epicpkmn11** [comment]
Here's a couple using [k6x8](https://littlelimit.net/k6x8.htm) combined with the default: [k6x8+default.zip](https://github.com/d0k3/GodMode9/files/7132318/k6x8%2Bdefault.zip)

The difference between `k6x8+default.frf` and `default+k6x8.frf` is just in the Kana and Cyrillic, `k6x8+default` uses k6x8's Kana and Cyrillic where `default+k6x8` uses the default's. Also, I moved the added characters to the very end of the PBM instead of the start this time fyi, not sure why I didn't think to do that before lol since this way the JIS X 0201 grid isn't messed with.

imo the two additional pixels width make a huge difference in the readability of the Kanji, most of these look like globs of pixels that barely resemble the kanji where 8x8 often actually look somewhat close, doesn't hurt to have options though. imo this one isn't worth putting in the resources folder, but if y'all like it feel free.

**Comment by TheShadowRunner** [comment]
Thank you very much for not only being fast but also giving choice !
"default+k6x8.frf" is perfect for me, exactly what I wished for. 
Kana in "k6x8+default" looks slightly less good imho.
Thanks again!

**Comment by heiyu-04** [comment]
I'm trying to make a font library with Chinese characters, but the display effect is very poor. Can you tell me the font of your scanning dot matrix

**Comment by d0k3** [comment]
Alright, I think we can close this, with Unicode support already beeing in GM9. Great work, @Epicpkmn11 !
