### ISSUE TITLE
How to add hidden titles to Home Screen?

### ISSUE THREAD

**Issue by Awesome-neos145** [d0k3/GodMode9#716]
How do I add hidden titles like the NNID Settings app the the Home Screen? Just curious.

BTW: The SD Card issue is fixed.

**Comment by d0k3** [comment]
Wrong place to ask this - there's a discussions area for that stuff, and you could also ask on the GodMode9 Discord. I don't think (= not know) what you intend to do is possible, though.

**Comment by TimmSkiller** [comment]
Those titles have a flag unset in their [SMDH](https://www.3dbrew.org/wiki/SMDH#Flags) so that they don't show up on the HOME Menu. The only ways this could be changed are to:
1. Make a forwarder that launches the app in question
2. Modify the SMDH, which would probably cause it to no longer work since those services require the system titles hashes match with what Nintendo has on their CDN, which would no longer be the case, as you would've modified them.
