### ISSUE TITLE
[FEATURE REQUEST] i18n language translation support.

### ISSUE THREAD

**Issue by James-Makoto** [d0k3/GodMode9#766]
**Got a great idea on how to improve GodMode9?**
Multi-language translation in Godemode9.

**Describe the feature you'd like**
The Unicode are supported now. Is it possible to support multi-language tranalstion like Godmode9i?

**Comment by d0k3** [comment]
I'm not against multi-language support in GodMode9, I just don't think the effort is worth it.

It would require lots of code changes (strings are hardcoded right now), and with the screen estate limitations of the 3DS, you'd not only need a good translation, but you'd also need to make sure everything fits and looks good. I may be wrong, but I think the number of users who actually can't handle english GM9 is very small.

Leaving this open cause I'd like to read other opinions. Also, if there's anyone who'd like to do this feature, just chime in here.

**Comment by Epicpkmn11** [comment]
I could add translation support, I already added it to [GodMode9i](https://github.com/DS-Homebrew/GodMode9i) since v3.0.0, so if you're curious how it would work I would probably do it very similar to that.

I don't think it should really be all that hard, if I do it like TWiLight Menu++/GodMode9i (GodMode9i's is more or less ripped straight from TWiLight lol) I think all that should be needed would be move all of the strings to be defined in some language file and to add some ini or such parser (any preference on ini, json, yaml, etc?) to read the translation files. Then to use a string you'd do `STR_FIRM_TOO_BIG` or such.

If you'd like that, do y'all have a preference for how the translations are managed? I always use Crowdin as it's free for open-source projects and works quite well imo, see [my profile](https://crowdin.com/profile/pk11) for everything I'm a manager on. It's *much* simpler for translators than just updating the ini and hoping people notice and know how to use git and also has some nice features like adding screenshots and descriptions for context and setting size limits on strings if needed and such.

If you want I can make a new project on my account for GM9 or if one of y'all want to do it it's fairly simple, just gotta make sure to do an [open-source request](https://crowdin.com/page/open-source-project-setup-request).

**Comment by d0k3** [comment]
@Epicpkmn11 - not against this, and I may also be wrong about the usefulness of it. It will still be a lot of work, I guess. Maybe show me, one example of how the source code would need to be changed before you start the big project?

**Comment by Epicpkmn11** [comment]
Opened #768 with the start of godmode.c done as an example, if it seems good I can continue on it.

imo translations are never really a bad thing (at least as long as they're done well), might not be all that necessary but if people are willing to translate it I don't see why not. I've seen Japanese, Spanish, Korean, and Russian sites on the GitHub traffic page for TWiLight Menu++ and Universal-Updater so there's definitely people who English isn't their main language who use these things.

**Comment by subad31155** [comment]
This feature is not crappy as well sometimes.??
