### ISSUE TITLE
[FEATURE REQUEST] Automatically account for FAT32 4GB size limit when dumping carts

### ISSUE THREAD

**Issue by mariomadproductions** [d0k3/GodMode9#780]
E.g. disallow dumping the non-split files if there isn't enough space, or maybe just add the last byte of the file to the txt metadata file?

**Comment by d0k3** [comment]
Are you requesting a feature or an antifeature? The 4GB-1 limit is not a storage space limit, it's the maximum size of a file in FAT32. I guess you already know, though.

Anyways, nope, I won't remove a feature that's in there for that long and that's used by many users. I can add the padding byte info (padding byte being the last byte in the cart rom memory) to the cart info, though.

Here's a test build, let me know if that works for you:
[GodMode9_Padding_Cartinfo.zip](https://github.com/d0k3/GodMode9/files/9161983/GodMode9_Padding_Cartinfo.zip)

**Comment by logandavis01** [comment]
Seems to work., only issue is the timestamp is on the same line as the padding byte instead of a new line.

Below is a screenshot of the hex editor showing the last byte, a screenshot of the .txt in gm9 and the .txt file itself for Xenoblade Chronicles 3D (4GB game).

![Last_Byte](https://user-images.githubusercontent.com/22719387/180342554-341ee17a-3efb-4de1-b2ef-cd6612503eaa.png)

![txt](https://user-images.githubusercontent.com/22719387/180343105-338d5c27-cfe7-4d03-a1db-7bd14f8a334a.png)

[000400000F700100_v00.txt](https://github.com/d0k3/GodMode9/files/9163789/000400000F700100_v00.txt)

**Comment by d0k3** [comment]
Thanks a lot for testing! Well, that's what happens if you're coding blind - I got no gamecarts for testing with me right now. Here's a new test build, with the output fixed:
[GodMode9_Padding_Cartinfo_fixed.zip](https://github.com/d0k3/GodMode9/files/9169489/GodMode9_Padding_Cartinfo_fixed.zip)

@mariomadproductions - is that a working solution for you?

**Comment by mariomadproductions** [comment]
Unfortunately I can't test myself as I don't have any 4GB carts, but yeah that looks good.

**Comment by d0k3** [comment]
> Unfortunately I can't test myself as I don't have any 4GB carts, but yeah that looks good.

Well, the padding byte is now always in there, regardless of the size of the cart. It's just the last byte in the rom. Fix commit is up now, additional testing is still appreciated.
