### ISSUE TITLE
[FEATURE REQUEST] Enable SafeMode9 by default for public releases

### ISSUE THREAD

**Issue by CalAlaera** [d0k3/GodMode9#850]
I think future versions of GM9 compiled for public release should have safe mode enabled by default.

For those who don't know: GodMode9 can be compiled in safe mode that prevents the user from breaking their Nintendo 3DS family console by deleting or overwriting certain system files by locking out high-level permissions at compile time.

With the loss of the Nintendo Network a large number of people are hacking their 3DS family console for the first time, and may not be familiar with the inner workings. Enabling safe mode by default would help protect them. For devs and folks who know what they're doing GM9 is a powerful tool and they'll need the higher levels, but maybe for the general public it should have the stabilisers on by default?

**Comment by Gruetzig** [comment]
I think that we should not not limit the usability of GodMode9 to prevent people them from "breaking" their console. 

There are warnings in place to prevent people who may not be familiar with the inner workings from breaking their console by accident. 
It will make troubleshooting pain, because you have to make people switch GodMode9 binaries just to edit system unique files or to restore a NAND backup.

**Comment by d0k3** [comment]
Exactly @Gruetzig - this has already been discussed enough. GM9 gives you a clear warning for everything dangerous that you could do, and you're even forced to enter a button combo (so that your toddler doesn't accidentaly wipe your precious handheld). If you can't handle GM9 like it is, you maybe should not install it on your console.
