### ISSUE TITLE
[FEATURE REQUEST] Remove or make digitizing cartridges optional, whilst maybe keeping a dumped game mounted

### ISSUE THREAD

**Issue by gexgamingyt** [d0k3/GodMode9#882]
**Got a great idea on how to improve GodMode9?**
Please remove digitization or make it optional if this idea of mounting 3DS/NDS games on the device becomes real development

**Describe the feature you'd like**
when your dumped game is still mounted you have to reboot then CFW will detect it like a virtual cartridge, it should also play as normal if you dumped both that 3ds/nds file and the save file. Also it's really up to the devs if they wanna remove or keep digitization or close this feature req.

**Describe alternatives you've considered**
Add a clear and concise description of any alternative solutions or features you've considered.

**Comment by ihaveamac** [comment]
Emulating a cartridge would be something that a custom firmware like Luma3DS has to implement. And because it's possible to install digital versions from game cards, this feature probably won't be implemented unless there's a really compelling case for it. In either case, this isn't something for GM9.

**Comment by Wolfvak** [comment]
As hax said, this is not up to us to implement.
