### ISSUE TITLE
SafeMode9 should allow writing to SysNAND if a9lh is installed

### ISSUE THREAD

**Issue by flarn2006** [d0k3/GodMode9#9]
Title.
The only difference from the regular GodMode9 would be that it doesn't allow removing A9LH, and doesn't allow SysNAND writes if A9LH isn't installed.

**Comment by d0k3** [comment]
I'm unsure about this. You know that without a NAND backup you are borked, too, if you break SysNAND enough? Because certain files are unique and required for it to even boot. Loose them -> bricked. Tbh, I think that anyone knowledgeable enough to require SysNAND write access can handle GodMode9 full well, with all the warnings and protections in there anyways.

I might improve on A9LH protection, though.

Leaving this open just in case there are other opinions.

**Comment by d0k3** [comment]
A9LH protection is improved on GodMode9 (it now has it's own write permission). As there is no new input on thi, I'm closing this issue. Feel free to reopen if anything new comes up.
