### ISSUE TITLE
Firm 0/1 restoring

### ISSUE THREAD

**Issue by trilleplay** [d0k3/GodMode9#94]
Hello! @d0k3, @TuxSH  pointed me to this for restoring the firm 0/1 backups. So how do i do that.

Thanks, Trille

**Comment by kade-robertson** [comment]
In theory, you should be able to do the following:

1. Run GM9 and go to your SD card drive (should be labelled [0:])
2. Use L to mark both firm0.bin and firm1.bin, then press Y to copy (if you only want to do one, just press Y on it)
3. Exit back to the main screen, and then go to your SysNAND Virtual drive (labelled [S:])
4. You should see on the bottom that Y will paste the contents. Press that, and enter whatever the required key combination is to unlock system writing.
5. You should be good to go (in theory)!

It goes without saying you should really have a backup for everything in case it goes sour.

**Comment by d0k3** [comment]
@kade-robertson - what you just suggested would lead to a brick. Be careful with such instructions.

@trilleplay - what legit reason is there to restore these backups other than a brick? Restoring these will be coming, via .gm9 script, and until then you'll have to wait. I could provide the instructions, but it's much too easy to do something wrong, so it's better to wait for a bit.

**Comment by kade-robertson** [comment]
@d0k3 So if you back up firm0 and immediately restore it you brick? Even if the files are identical? Why?

(Didn't mean to provide bad instruction, I did leave warnings in it though)

**Comment by james-d-elliott** [comment]
Pretty sure the backups are raw, GM9 expects them to be decrypted, so it encrypts them, meaning already encrypted data is encrypted again.

**Comment by kade-robertson** [comment]
Ah, OK. So if you were to copy over a decrypted firm0 it would have been fine?

**Comment by d0k3** [comment]
@kade-robertson - yes, that's the problem. The backups SafeB9SINstaller does are encrypted, while the access in GM9 is decrypted. These backups are encrypted for a reason, cause, *if* something actually goes wrong, these backups can easily be restored to the places they belong to (f.e. with a hardmod) and don't need to be reencrypted.

@trilleplay - look [here](https://www.reddit.com/r/3dshacks/comments/6h3b4y/godmode9_scripting_support_open_beta_test_build/). The hardmod GM9 scripts pack contains a revert_sb9si script (one for SB9SI pre 0.0.7, one for current). It is not recommended you use this if you made any bigger modifications to your system since you installed or if you even changed something about these backups in the meantime.

Other than this, this should work. I recommend you do a full NAND backup in GM9 before you run the script and verify (in the A button menu...) S:/firm0.bin before rebooting.

Are you reverting to stock, A9LH or an earlier version of b9s? Cause, in the case of an earlier b9s version it is recommended to use SafeB9SInstaller instead.

**Comment by d0k3** [comment]
[These scripts](https://transfer.sh/uJ3ZL/godmode9_scripts.zip) restore FIRM0 / FIRM1 or revert to stock. Closing this now
