### ISSUE TITLE
Request: Can you make an updated Godmode9 EmuNAND guide?

### ISSUE THREAD

**Issue by kamenrider-darkglass** [d0k3/GodMode9#95]
The SD format menu has the following:

No EmuNAND
SysNAND size (min)
SysNAND size (full)
1GB (legacy size)
2GB (legacy size)
User input...

The reason why I am making this request is because Godmode9 isn't exactly user-friendly. I assume that "SysNAND size" refers to the creation of redNANDs and "legacy size" refers to the creation of Gateway-type emuNANDs. The problem is that I don't know if they are for sure nor am I knowledgeable on what results I get between min and full for the SysNAND options and 1GB and 2GB for the legacy size option. 

I want to make a Gateway-type EmuNAND so that I would be able to use my Gateway Card. This is so much easier with EmuNAND9. Can't you release a new EmuNAND9 release that is compatible with boot9strap? You made one for hourglass9 so it shouldn't be too much trouble to make one rather than trying to write a guide on the EmuNAND specific features of Godmode9.

**Comment by d0k3** [comment]
Three(!) issues opened for one problem and on top of that the frowned upon "I did things like that for ages, and I'm too lazy to do it another way". Oh well...

You can do a guide yourself. Make something that is found via Google (f.e. on gbatemp), and help other users. The one thing I agree on in this issue is that renaming the options may make sense.

You need SysNAND size (min) for RedNAND, and you need SysNAND size (full) for EmuNAND.
